### ISSUE TITLE
Getting the proper permissions using this method?

### ISSUE THREAD

**Issue by robmpreston** [IdoTene/XamarinFormsNativeFacebook#1]
Hey,

I've been using your code as a base while working on a Xamarin.Forms app - just curious how I would use this to get the proper permissions without having to make two calls? I know in Objective-C's FB SDK you can call Open with permissions passed as parameters, but I don't see that in Xamarins.

**Comment by idotene** [comment]
I wanted to make to calls because of the server side should keep the data.
If you want to use the data in the client in the existing session, you can add to FacebookLoginButtonRendererIos.cs The following code:

```
 private void HandleFacebookLoginClicked()
        {
            if (FBSession.ActiveSession.IsOpen)
            {
                FBRequestConnection.GetMe(
                          delegate(FBRequestConnection connection, NSObject result, NSError nsError)
                          {
                              //Just add your code here
                          });
            }
            else
            {
                FBSession.ActiveSession.Open(FBSessionLoginBehavior.UseSystemAccountIfPresent, (aSession, status, error) =>
                {
                    if (error == null)
                    {
                        FBRequestConnection.GetMe(
                            delegate(FBRequestConnection connection, NSObject result, NSError nsError)
                            {
                                //Just add your code here
                            });

                    }
                });
            }
```

**Comment by robmpreston** [comment]
Thanks - I assume that’s just a get call though right? You still need to request specific permissions (i.e. if i want the users email)

**Comment by idotene** [comment]
Yeah you can invoke  FBSession.ActiveSession.RequestNewReadPermissions for that

**Comment by robmpreston** [comment]
That’s what I was looking at - I just assumed that would make a separate redirect or something (i.e. request and then request again) - if that’s not the case I’ll do that. Thanks for getting back to me.

**Comment by IdoTene** [comment]
Sure let me know if it works for you

**Comment by robmpreston** [comment]
Hey,

Sorry to bug you but maybe you can help. When I try to invoke to modify Read Permissions I am getting an error that it can’t call it while its already in progress with another. I’m assuming its because the session open isn’t done yet. How can I time it to make sure that it isn’t an issue?

Rob

**Comment by idotene** [comment]
I'll try to take a look into it on Sunday..
Cheers

**Comment by robmpreston** [comment]
Hey man,

Hope all is well. Did you ever have a minute to look at this?

Rob

**Comment by idotene** [comment]
I've managed to add permissions as follows:
         private void HandleFacebookLoginClicked()
             {
                     if (FBSession.ActiveSession.IsOpen)
                     {
                              FBSession.ActiveSession.CloseAndClearTokenInformation();
                      }

```
        FBSession.ActiveSession.Open(FBSessionLoginBehavior.UseSystemAccountIfPresent, (aSession, status, error) =>
        {
            if (aSession.State == FBSessionState.OpenTokenExtended)
            {
                var permissions = new string[] { "friends_hometown" };
                FBSession.ActiveSession.RequestNewReadPermissionsAsync(permissions).ContinueWith(p =>
                {
                    App.PostSuccessFacebookAction(aSession.AccessTokenData.AccessToken);
                });
            }


        });
```

**Comment by robmpreston** [comment]
Appreciate it. I’ll give it a try.

**Comment by robmpreston** [comment]
This is old but I finally got around to trying it..

When I use the code above I get this message in my console:

 FBSDKLog: Cannot use the Facebook app or Safari to authorize,fb is not registered as a URL Scheme

Saw some suggestion on google but had no luck, any ideas?
